name: Build and Deploy Spring Boot App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Create .env file with secrets
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

      - name: Secure Deploy
        env:
          OCI_HOST: ${{ secrets.OCI_DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.OCI_DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -t rsa $OCI_HOST >> ~/.ssh/known_hosts

         
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$OCI_HOST "mkdir -p ~/app_deploy"

        
          scp -i ~/.ssh/id_rsa build/libs/*.jar $DEPLOY_USER@$OCI_HOST:~/app_deploy/app.jar

         
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$OCI_HOST "sudo bash -c 'cat > /etc/systemd/system/backer-blog.service << EOF
          [Unit]
          Description=Backer Blog Application
          After=network.target
  
          [Service]
          User=$DEPLOY_USER
          WorkingDirectory=/home/$DEPLOY_USER/app_deploy
          ExecStart=/usr/bin/java -jar app.jar
          SuccessExitStatus=143
          TimeoutStopSec=10
          Restart=on-failure
          RestartSec=5
          
          [Install]
          WantedBy=multi-user.target
      
    
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$OCI_HOST "sudo systemctl daemon-reload && sudo systemctl enable backer-blog && sudo systemctl restart backer-blog && sudo journalctl -u backer-blog -n 50"